FROM ubuntu:latest

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        build-essential \
        libsnmp-dev \
        python3 \
        python3-dev \
        python3-setuptools \
        snmp \
        snmpd \
        valgrind \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /src
COPY . .

CMD ["sh", "netsnmp/tests/system/run.sh"]
